### ISSUE TITLE
预览问题

### ISSUE THREAD

**Issue by lcw552003428** [galacean/effects-runtime#1]
为何在点击预览后 上传打包的文件显示 离线产物解析失败？

**Comment by luckygcb** [comment]
是在 Galacean Effects 编辑器导出的产物 ZIP 包吗

**Comment by lcw552003428** [comment]
好的 已经解决。这个预览 需要导出文件再导入一遍。为啥要多此一举呢，明明时间轴就可以预览整体效果了。这个功能是出于什么考虑的&nbsp;


-
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月22日(星期三) 晚上7:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [galacean/effects-runtime] 预览问题 (Issue #1)





 
是在 Galacean Effects 编辑器导出的产物 ZIP 包吗

**Comment by luckygcb** [comment]
> 好的 已经解决。这个预览 需要导出文件再导入一遍。为啥要多此一举呢，明明时间轴就可以预览整体效果了。这个功能是出于什么考虑的&nbsp; - ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年11月22日(星期三) 晚上7:19 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [galacean/effects-runtime] 预览问题 (Issue #1) 是在 Galacean Effects 编辑器导出的产物 ZIP 包吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Galacean Effects 编辑器在导出产物时，会对合成数据和资源进行优化，仅保留播放器需要使用到的数据和资源，而非项目中的所有数据和资源。为了方便确认导出产物的实际效果和设计师预期的效果是一致的，我们提供了这个产物的预览功能。
