### ISSUE TITLE
[Bug] 小程序，安装教程使用，构建npm后显示module 'pages/index/@galacean/appx-adapter/weapp.js' is not defined, require args is '@galacean/appx-adapter/weapp'

### ISSUE THREAD

**Issue by SSStq1314** [galacean/effects-runtime#114]
### 🔎 搜索关键词

微信小程序 appx-adapter/weapp

### 🕗 版本信息

1.1.5

### 🖥️ 平台信息

- [ ] iOS
- [ ] Android
- [ ] Web
- [X] 小程序（支付宝/微信）
- [ ] 微信小游戏
- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] Other

### 💻 Sample Code

node_modules/@galacean/effects-math/index.js: 未找到npm包入口文件
node_modules/@galacean/effects-webgl/index.js: 未找到npm包入口文件
`
  "dependencies": {
    "@galacean/appx-adapter": "^0.0.9",
    "@galacean/effects": "^1.1.5"
  }
`

`
VM3651:11 页面【pages/index/index]错误:
 Error: module 'pages/index/@galacean/appx-adapter/weapp.js' is not defined, require args is '@galacean/appx-adapter/weapp'
    at q (WASubContext.js?t=wechat&s=1705295175808&v=3.3.1:1)
    at n (WASubContext.js?t=wechat&s=1705295175808&v=3.3.1:1)
    at index.js? [sm]:2
    at WASubContext.js?t=wechat&s=1705295175808&v=3.3.1:1
    at p.runWith (WASubContext.js?t=wechat&s=1705295175808&v=3.3.1:1)
    at q (WASubContext.js?t=wechat&s=1705295175808&v=3.3.1:1)
    at <anonymous>:8:5
    at evaluateRes (index.js:1)
    at index.js:1
    at Object.invoke (index.js:1)(env: macOS,mp,1.06.2401020; lib: 3.3.1)
`
<img width="354" alt="截屏2024-01-15 13 45 52" src="https://github.com/galacean/effects-runtime/assets/20391773/2937708a-fdf0-4d20-8a63-7c5459c6a6e9">

### 🙂 预期行为

正常加载并播放资源

### 🙁 实际行为

报错，无法正常引用

### ⏯ Steps to Reproduce

https://developers.weixin.qq.com/s/YuJLbemR73OZ

加载代码片段到本地后，执行npm install ，然后使用微信开发者工具-工具-构建npm

**Comment by yiiqii** [comment]
Galacean Effects 对小程序的适配包使用了 `package.json` `exports`，NodeJS v12.7.0 和 Typescript v4.7 及以上才支持，同时 `tsconfig.json` 的 `module` 需配置为 `ESxxx`（如：`ESNext`）。

**Comment by SSStq1314** [comment]
所以我这边要做什么操作，我是用正常的小程序创建新项目，然后npm 引用，构建npm，或者你这边有完成的代码示例吗？

**Comment by yiiqii** [comment]
> 所以我这边要做什么操作，我是用正常的小程序创建新项目，然后npm 引用，构建npm，或者你这边有完成的代码示例吗？

你是纯 js 的项目还是 ts 的？如果是 js 的话尝试这样引入：
``` ts
import { registerCanvas } from '@galacean/appx-adapter/dist/weapp';
import { Player } from '@galacean/effects/dist/weapp';
```

**Comment by yiiqii** [comment]
> 所以我这边要做什么操作，我是用正常的小程序创建新项目，然后npm 引用，构建npm，或者你这边有完成的代码示例吗？

请问这个问题解决了吗？

**Comment by yiiqii** [comment]
> 所以我这边要做什么操作，我是用正常的小程序创建新项目，然后npm 引用，构建npm，或者你这边有完成的代码示例吗？

可以参考微信小程序的 demo：https://github.com/galacean/galacean-effects-miniprogram-demo
原生的可以用这个姿势：
<img width="863" alt="image" src="https://github.com/galacean/effects-runtime/assets/5226170/7ba74011-ace0-4c65-8cb3-792dec96d614">

**Comment by ToninZhao** [comment]
> > 所以我这边要做什么操作，我是用正常的小程序创建新项目，然后npm 引用，构建npm，或者你这边有完成的代码示例吗？
> 
> 可以参考微信小程序的 demo：https://github.com/galacean/galacean-effects-miniprogram-demo 原生的可以用这个姿势： <img alt="image" width="863" src="https://private-user-images.githubusercontent.com/5226170/296706592-7ba74011-ace0-4c65-8cb3-792dec96d614.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzY3MzgwNDUsIm5iZiI6MTc3NjczNzc0NSwicGF0aCI6Ii81MjI2MTcwLzI5NjcwNjU5Mi03YmE3NDAxMS1hY2UwLTRjNjUtOGNiMy03OTJkZWM5NmQ2MTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDQyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA0MjFUMDIxNTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTU4MGIwMGVlYjA5NGZiMjJmYmUyY2U0MTQwYWM1Y2I5NmJmMGJhMDAwZjk3NGFlN2M2YTM3YjY1YjVlMzhlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.Ykd6m7tyEnRlqmZcihUCxi7Bq8yiXuWE1QPX4D0cvbA">

使用 npm 引入，我也遇到同样的问题。使用编译好的 js 库没有问题。但是编译好的 js 库体积有600多k，在原来的主包引入使用，代码体积受限，有好的解决方案吗？

**Comment by yiiqii** [comment]
@ToninZhao 官方的 demo 你本地运行看看有没有问题，理论不会有问题的，如果还是不行可以贴下微信小程序的分享链接

**Comment by ToninZhao** [comment]
> [@ToninZhao](https://github.com/ToninZhao) 官方的 demo 你本地运行看看有没有问题，理论不会有问题的，如果还是不行可以贴下微信小程序的分享链接

官方小程序 npm 包管理的 demo运行有问题，报错内容：sh: rollup: command not found
我在分包引入 mp-weapp-galacean-effects.js 文件，在主包异步调用，解决了体积受限的问题。

**Comment by yiiqii** [comment]
报错内容：sh: rollup: command not found
这个是前端基础，你要自己学习解决，官方 demo 很多人已经跑过，不会有问题的
@ToninZhao

**Comment by ToninZhao** [comment]
> 报错内容：sh: rollup: command not found 这个是前端基础，你要自己学习解决，官方 demo 很多人已经跑过，不会有问题的 [@ToninZhao](https://github.com/ToninZhao)

找到问题了，用微信开发者工具的终端执行 npm install 下载的 node_modules 是空的，没报错。换 vscode 执行就可以了

<img width="425" height="178" alt="Image" src="https://github.com/user-attachments/assets/9bd0442a-04d0-4a6a-afb8-e0aa2a6d9d9b" />
