### ISSUE TITLE
[Bug] 对 player 实例进行销毁后，报错问题

### ISSUE THREAD

**Issue by wangbo163com** [galacean/effects-runtime#137]
### 🔎 搜索关键词

1.对player实例进行销毁后，报错问题。2.减少一些无用的conslog.log

### 🕗 版本信息

1.1.5

### 🖥️ 平台信息

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] 小程序（支付宝/微信）
- [ ] 微信小游戏
- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Other

### 🙂 预期行为

应该是正常销毁

### 🙁 实际行为

![lQLPKcwiVUuIe7PNATrNBVSwOi5bC6BCwwkFncoq4bDzAA_1364_314](https://github.com/galacean/effects-runtime/assets/157365700/be826e27-2cb8-48a5-8732-c544e9c6dcb7)

### ⏯ 复现步骤

player.value && (await player.value.dispose());

**Comment by liuxi150** [comment]
看着是创建两个Player加载分别加载两个JSON文件，然后销毁一个Player后出错？
可以提供下可运行的最小场景吗，我们使用时基本遇到销毁的错误。
